projectDemoVer_2/slnMVCDemoVer_2/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace slnMVCDemosuru.Controllers
{
    public class RecordController : Controller
    {
        public ActionResult Rank()
        {
            var rank = from record in (new DbLINQDataContextDataContext()).personal_sport_menu select record ;
            return View(rank);
        }
        public ActionResult UserData()
        {
            var rank = from UserData in (new DbLINQDataContextDataContext()).bjuser select UserData;
            return View(rank);
        }
        public ActionResult update (personal_sport_menu record)
        {
            DbLINQDataContextDataContext db = new DbLINQDataContextDataContext();
            personal_sport_menu data = db.personal_sport_menu.FirstOrDefault(m => m.p_menu_num == record.p_menu_num);
            //bjuser user = db.bjuser.FirstOrDefault(m => m.user_id == User.user_id);
            if (data != null)
            {
                data.user_id = record.user_id;
                data.spdate = record.spdate;
                data.SportID = record.SportID;
                data.distance = record.distance;
                data.times = record.times;
                db.SubmitChanges();
            }               
            
                    
            return new RedirectResult("Rank");
        }
    
    // GET: Record
    public ActionResult Index()
        {
            return View();
        }
    }
}

projectDemoVer_2/slnMVCDemoVer_2/Views/Record/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

projectDemoVer_2/slnMVCDemoVer_2/Views/Record/Rank.cshtml
@model IEnumerable<personal_sport_menu>
@{
    ViewBag.Title = "Rank";
}

<h3>用戶資料列表</h3>
<p>
    <a href="~/A/New">註冊</a>
</p>


<h2>Rank 第一版(列資料)</h2>

<table border="1">
    <tr>
        <td>用戶ID</td>
        <td>運動日期</td>
        <td>運動項目</td>
        <td>運動距離</td>
        <td>運動時間</td>
        <td>修改</td>
    </tr>
   
        @{
            foreach (personal_sport_menu record in Model)
            {
                <tr>
                    <td>@record.user_id.ToString()</td>
                    <td>@record.spdate.ToString()</td>
                    <td>@record.SportID.ToString()</td>
                    <td>@record.distance.ToString()</td>
                    <td>@record.times.ToString()</td>
                    <td>@Html.ActionLink("修改", "update", "Record", new { user_id=record.user_id },null )td>
                </tr>
            }
        }
           
</table>
    

projectDemoVer_2/slnMVCDemoVer_2/Views/Record/UserData.cshtml
@model IEnumerable<bjuser>
@{
    ViewBag.Title = "UserData";
}

<h2>UserData</h2>
<table border="1">
    <tr>
        <td>帳號</td>
        <td>密碼</td>
        <td>信箱</td>
        <td>生日</td>
       
    </tr>
    @{ 
        foreach(bjuser user in Model)
        {
            <tr>
                <td>@user.u_name.ToString()</td>
                <td>@user.u_password.ToString()</td>
                <td>@user.u_email.ToString()</td>
                <td>@user.u_birth.ToString()</td>
                
            </tr>
        }
    }
</table>